project:
  type: manuscript
  output-dir: docs

manuscript:
  article: index.qmd
  code-links: 
    - text: Github
      icon: github
      href:  https://github.com/juliam98/
    - text: Home
      icon: house
      href: https://juliam98.github.io/
  meca-bundle: true


format:
  html:
    toc: true
    toc-location: left
    fig-width: 5
    fig-height: 6
    filters:
    - latex-environment
    commands: [gls]
  docx: default
  pdf: 
    toc: false
    number-sections: false
    colorlinks: true
    cite-method: biblatex
    biblatexoptions: style=nature, 
    include-in-header:
      - text: |
          \usepackage{pgfgantt}
          \usepackage[dvipsnames]{xcolor}
          \definecolor{myblue}{rgb}{0.592, 0.737, 0.878}
          \usepackage[acronym, nonumberlist, nopostdot, hyperfirst=false]{glossaries}
          \usepackage{glossary-mcols}
          \loadglsentries{files/abbreviations}
          \setkomafont{title}{\normalfont\large\color{myblue}}
          \setkomafont{section}{\normalfont\large\color{myblue}}
          \setkomafont{subsection}{\normalfont\normalsize\color{myblue}}

execute:
  freeze: auto



